### ISSUE TITLE
Run in single cookbook repositories

### ISSUE THREAD

**Issue by jeroenj** [mmozuras/pronto-foodcritic#1]
Right now it seems that the runner is built for chef repo's which contain multiple cookbooks (or roles) as https://github.com/mmozuras/pronto-foodcritic/blob/master/lib/pronto/foodcritic.rb#L35 expects the path to include `cookbook`.

However when all your cookbooks are separated into single repositories cookbook might not always appear in the path. For example when your repository name does not include `-cookbook` or when you're running it on a CI server which does not use project names internally (like GitLab CI).

I'd say to remove that check alltogether and just run foodcritic on all files. Does that sound reasonable to you?

**Comment by mmozuras** [comment]
> I'd say to remove that check alltogether and just run foodcritic on all files. Does that sound reasonable to you?

That can result in false positives. I'll make it configurable instead. Sounds good?

**Comment by jeroenj** [comment]
Sounds good. In which case would it result false positives?

Sorry for the delay, I was on holiday the past two weeks. :)

**Comment by jeroenj** [comment]
While working on that it might be interesting to add an option to define foodcritic tags (and other options) too. Since it does not use a config file to enable or disable rules it needs to be passed in the options of `FoodCritic::Linter#check`. (e.g. https://github.com/jeroenj/pronto-foodcritic/commit/20bdaed79bd722cf681ed67b9573f6ec7a905c8c)

**Comment by ashkulz** [comment]
Considering that FoodCritic is now archived, I'm closing this issue.
