### ISSUE TITLE
Depends on pronto 0.4.0

### ISSUE THREAD

**Issue by elliotthilaire** [mmozuras/pronto-foodcritic#2]
Hi @mmozuras, 

I tried to install ALL the runners just to see what would happen.  I had to uninstall pronto-foodcritic because of the below conflict (also had to uninstall pronto-spell and pronto-fasterer for the same reason).

```
.rvm/rubies/ruby-2.1.4/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2112:in `raise_if_conflicts': Unable to activate pronto-spell-0.4.1, because pronto-0.5.3 conflicts with pronto (~> 0.4.0) (Gem::ConflictError)
```

Is a fix for this as simple as updating the .gemspec file to ~>0.5.0?

**Comment by mmozuras** [comment]
Hi,

@elliotthilaire yes, that's the idea. When releasing newest version of Pronto, I missed this gem and failed to make it compatible with 0.5.0 :bow:.

Done now and released :smile:.

**Comment by elliotthilaire** [comment]
Thanks for the update!
Now I know how to fix this for next time.
