### ISSUE TITLE
Cannot run pronto-rails_schema and pronto-jscs

### ISSUE THREAD

**Issue by ebouchut** [mmozuras/pronto-foodcritic#3]
Hi @mmozuras,

First off thanks for the useful gem and the bunch of integration provided.

While installing all the runners, I noticed two of them (`pronto-jscs` and `pronto-rails_schema`) require an older  version of pronto which seems to conflict with the latest version installed `0.6.0`.

```
/Users/eric/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2288:in `raise_if_conflicts': Unable to activate pronto-brakeman-0.6.0, because pronto-0.5.3 conflicts with pronto (~> 0.6.0) (Gem::ConflictError)
```

```
gem dependency -R pronto

Gem pronto-jscs-0.0.5
  bundler (~> 1.10, development)
  pronto (~> 0.5.0)
  rake (~> 10.0, development)
  rspec (~> 3.3, development)
  rspec-its (~> 1.2, development)

Gem pronto-rails_schema-0.5.0
  bundler (~> 1.10, development)
  pronto (~> 0.5.0)
  rake (~> 10.0, development)
  rspec (~> 3.3, development)

```

**Comment by ebouchut** [comment]
Closing as this is not the correct repo for posting this.
Sorry  about this.

**Comment by ebouchut** [comment]
I didn't noticed you had already opened issues about this:
- spajus/pronto-jscs#1
- raimondasv/pronto-rails_schema#1

**Comment by mmozuras** [comment]
@ebouchut yes, you are correct - feel free to ping them in those issues 😄
